---
# Tasks for pre-introspection
- name: Pre-Introspection
  block:
    - name: Set Pre-Introspection
      shell: |
        "source {{ stack_user_home }}/stackrc && openstack workflow execution create tripleo.validations.v1.run_groups '{'group_names':['pre-introspection']}'"

    - name: Check Pre-Introspection
      shell: |
        "source {{ stack_user_home }}/stackrc && openstack workflow execution list -f json -c 'Workflow name'|grep groups"
      register: pre_intro

    - name: Pre-Introspection Output
      debug:
        var: pre_intro.stdout_lines
  tags: pre_intro
# END Pre-Introspection BLOCK

# Tasks for configuring DNS
- name: DNS
  block:
    - name: Check DNS
      shell: "source {{ stack_user_home }}/stackrc && openstack subnet show ctlplane-subnet -f json -c dns_nameservers|jq '.dns_nameservers'"
      register: dns_check
      changed_when: false

    - name: Set DNS For The Control Plane Network
      shell: "source {{ stack_user_home }}/stackrc && openstack subnet set ctlplane-subnet --dns-nameserver {{ item }}"
      when: dns_check.stdout.find(item) == -1
      with_items:
        - "{{ openstack_preconfig_dnsserver1 }}"
        - "{{ openstack_preconfig_dnsserver2 }}"

    - name: Verify DNS For The Control Plane Network
      shell: "source {{ stack_user_home }}/stackrc && openstack subnet show ctlplane-subnet  |grep dns"
      register: dns
      changed_when: false
      
    - name: DNS Output
      debug:
        var: dns.stdout_lines
  tags: dns
# END DNS BLOCK